server:
  port: 8082

spring:
  application:
    name: notification
  datasource:
    username: 'amigoscode'
    url: jdbc:postgresql://postgres:5432/notification
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop # don't do it on production or environment where you want to keep your data
    show-sql: 'true'
  zipkin:
    base-url: http://zipkin:9411 # defult
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true # default
    register-with-eureka: true # default
    enabled: false # for k8s
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing.key